---
development:
  cloud_name: dsn2mbfvg
  api_key: '986113899878467'
  api_secret: wWSpcQs_mdkbQqEmhlO-gRLTfIc
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dsn2mbfvg
  api_key: '986113899878467'
  api_secret: wWSpcQs_mdkbQqEmhlO-gRLTfIc
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dsn2mbfvg
  api_key: '986113899878467'
  api_secret: wWSpcQs_mdkbQqEmhlO-gRLTfIc
  enhance_image_tag: true
  static_file_support: false
